# Generated by Django 5.0.4 on 2024-04-07 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numéro_de_rue', models.PositiveIntegerField()),
                ('rue', models.CharField(max_length=255)),
                ('appartement', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ville', models.CharField(max_length=255)),
                ('code_postal', models.CharField(max_length=6)),
                ('province', models.CharField(choices=[('NL', 'Terre-Neuve-et-Labrador'), ('PE', 'Île-du-Prince-Édouard'), ('NS', 'Nouvelle-Écosse'), ('NB', 'Nouveau-Brunswick'), ('QC', 'Québec'), ('ON', 'Ontario'), ('MB', 'Manitoba'), ('SK', 'Saskatchewan'), ('AB', 'Alberta'), ('BC', 'Colombie-Britannique'), ('YT', 'Yukon'), ('NT', 'Territoires du Nord-Ouest'), ('NU', 'Nunavut')], max_length=2)),
            ],
            options={
                'ordering': ['rue', 'numéro_de_rue'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prénom', models.CharField(max_length=50)),
                ('courriel', models.EmailField(max_length=254, unique=True)),
                ('téléphone_maison', models.CharField(max_length=255)),
                ('téléphone_cellulaire', models.CharField(max_length=255)),
                ('télécopieur', models.CharField(max_length=255)),
                ('date_de_naissance', models.DateField()),
                ('ramq', models.CharField(max_length=14)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unité_de_soins.adresse')),
            ],
            options={
                'ordering': ['nom', 'prénom'],
            },
        ),
        migrations.CreateModel(
            name='DossierMédical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dossier', models.CharField(max_length=24)),
                ('chambre', models.CharField(max_length=6)),
                ('incontinence', models.CharField(choices=[('sèche', 'Sèche'), ('humide', 'Humide'), ('peu', '<1/2 plein'), ('beaucoup', '>1/2 plein'), ('changer', 'Changer')], max_length=11)),
                ('détection_chute', models.CharField(choices=[('normal', 'Normal'), ('avertissement', 'Avertissement'), ('alerte', 'Alerte'), ('pas de données', 'Pas de données'), ('pas de suivi', 'Pas de suivi')], max_length=14)),
                ('amnamèse_ic', models.CharField(choices=[('normal', 'Normal'), ('avertissement', 'Avertissement'), ('alerte', 'Alerte'), ('pas de données', 'Pas de données'), ('pas de suivi', 'Pas de suivi')], max_length=14)),
                ('fréquence_cardiaque', models.CharField(choices=[('normal', 'Normal'), ('avertissement', 'Avertissement'), ('alerte', 'Alerte'), ('pas de données', 'Pas de données'), ('pas de suivi', 'Pas de suivi')], max_length=14)),
                ('saturation', models.CharField(choices=[('normal', 'Normal'), ('avertissement', 'Avertissement'), ('alerte', 'Alerte'), ('pas de données', 'Pas de données'), ('pas de suivi', 'Pas de suivi')], max_length=14)),
                ('pression_artérielle', models.CharField(choices=[('normal', 'Normal'), ('avertissement', 'Avertissement'), ('alerte', 'Alerte'), ('pas de données', 'Pas de données'), ('pas de suivi', 'Pas de suivi')], max_length=14)),
                ('température_corporelle', models.CharField(choices=[('normal', 'Normal'), ('avertissement', 'Avertissement'), ('alerte', 'Alerte'), ('pas de données', 'Pas de données'), ('pas de suivi', 'Pas de suivi')], max_length=14)),
                ('fréquence_respiratoire', models.CharField(choices=[('normal', 'Normal'), ('avertissement', 'Avertissement'), ('alerte', 'Alerte'), ('pas de données', 'Pas de données'), ('pas de suivi', 'Pas de suivi')], max_length=14)),
                ('adhérence_rx', models.CharField(choices=[('normal', 'Normal'), ('avertissement', 'Avertissement'), ('alerte', 'Alerte'), ('pas de données', 'Pas de données'), ('pas de suivi', 'Pas de suivi')], max_length=14)),
                ('grandeur', models.DecimalField(decimal_places=2, max_digits=5)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_création', models.DateTimeField(auto_now_add=True)),
                ('dernier_changement', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='unité_de_soins.patient')),
            ],
            options={
                'ordering': ['chambre'],
            },
        ),
        migrations.CreateModel(
            name='PersonnelSoignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EIN', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=50)),
                ('prénom', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='')),
                ('courriel', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('DT', 'Diététiste'), ('DR', 'Docteur'), ('ERG', 'Ergothérapeute'), ('INF', 'Infirmier/Infirmière'), ('INFA', 'Infirmier auxiliaire/Infirmière auxiliaire'), ('INH', 'Inhalothérapeute'), ('OPT', 'Optométriste'), ('ORT', 'Orthophoniste'), ('PHA', 'Pharmacien'), ('PHY', 'Physiothérapeute'), ('POD', 'Podiatre'), ('PSY', 'Psychologue')], max_length=4)),
                ('département', models.CharField(max_length=255)),
                ('patients', models.ManyToManyField(to='unité_de_soins.patient')),
            ],
            options={
                'ordering': ['nom', 'prénom'],
            },
        ),
    ]
