# Generated by Django 5.0.4 on 2024-04-07 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unité_de_soins', '0002_alter_dossiermédical_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossiermédical',
            old_name='date_création',
            new_name='date_créé',
        ),
        migrations.RenameField(
            model_name='dossiermédical',
            old_name='grandeur',
            new_name='taille',
        ),
    ]
