# Generated by Django 5.0.4 on 2024-04-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unité_de_soins', '0003_rename_date_création_dossiermédical_date_créé_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiermédical',
            name='chambre',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='dossiermédical',
            name='id_dossier',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nom',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prénom',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ramq',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='télécopieur',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='téléphone_cellulaire',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='téléphone_maison',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='personnelsoignant',
            name='EIN',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
