# Generated by Django 5.0.4 on 2024-04-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unité_de_soins', '0004_alter_dossiermédical_chambre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiermédical',
            name='chambre',
            field=models.CharField(max_length=5),
        ),
    ]
