# Generated by Django 5.0.4 on 2024-04-11 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unité_de_soins', '0005_alter_dossiermédical_chambre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossiermédical',
            options={'ordering': ['id_dossier'], 'verbose_name_plural': 'Dossier médicaux'},
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('lieu', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('durée', models.DurationField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='unité_de_soins.patient')),
                ('personnel_soignant', models.ManyToManyField(to='unité_de_soins.personnelsoignant')),
            ],
        ),
    ]
