# Generated by Django 5.0.4 on 2024-04-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unité_de_soins', '0007_alter_rendezvous_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='personnel_soignant',
            field=models.ManyToManyField(related_name='rendez_vous', to='unité_de_soins.personnelsoignant'),
        ),
    ]
