# Generated by Django 5.0.4 on 2024-04-18 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unité_de_soins', '0008_alter_rendezvous_personnel_soignant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnelsoignant',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name_plural': 'Personnel soignant'},
        ),
        migrations.RemoveField(
            model_name='personnelsoignant',
            name='courriel',
        ),
        migrations.RemoveField(
            model_name='personnelsoignant',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='personnelsoignant',
            name='prénom',
        ),
        migrations.AddField(
            model_name='personnelsoignant',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
