# Generated by Django 5.0.4 on 2024-04-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unité_de_soins', '0009_alter_personnelsoignant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnelsoignant',
            options={'verbose_name_plural': 'Personnel soignant'},
        ),
    ]
