# Generated by Django 5.0.4 on 2024-04-20 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unité_de_soins', '0010_alter_personnelsoignant_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnelsoignant',
            name='photo',
        ),
        migrations.CreateModel(
            name='PersonnelSoignantPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='unité_de_soins/photos')),
                ('personnel_soignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='unité_de_soins.personnelsoignant')),
            ],
        ),
    ]
