# Generated by Django 5.0.4 on 2024-04-20 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unité_de_soins', '0011_remove_personnelsoignant_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelSoignantPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='unité_de_soins/photos')),
                ('personnel_soignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='unité_de_soins.personnelsoignant')),
            ],
        ),
        migrations.DeleteModel(
            name='PersonnelSoignantPhoto',
        ),
    ]
