# Generated by Django 5.0.4 on 2024-04-22 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unité_de_soins', '0012_personnelsoignantphotos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonnelSoignantPhotos',
            new_name='PersonnelSoignantPhoto',
        ),
        migrations.RenameField(
            model_name='personnelsoignantphoto',
            old_name='photos',
            new_name='photo',
        ),
    ]
